// Code generated by queryx, DO NOT EDIT.

package db

import (
	"fmt"
	"snap/db/queryx"
	"strings"
)

type Deck struct {
	ID        int64           `json:"id" db:"id"`
	Name      queryx.String   `json:"name" db:"name"`
	CreatedAt queryx.Datetime `json:"createdAt" db:"created_at"`
	UpdatedAt queryx.Datetime `json:"updatedAt" db:"updated_at"`
	DeckCards []*DeckCard     `json:"deckCards"`
	Cards     []*Card         `json:"cards"`

	schema  *queryx.Schema
	queries Queries
}

// String implements the stringer interface.
func (d *Deck) String() string {
	var b strings.Builder
	b.WriteString("(Deck ")
	b.WriteString(fmt.Sprintf("id: %v", d.ID))
	b.WriteString(", ")
	b.WriteString(fmt.Sprintf("name: %s", d.Name))
	b.WriteString(", ")
	b.WriteString(fmt.Sprintf("created_at: %v", d.CreatedAt))
	b.WriteString(", ")
	b.WriteString(fmt.Sprintf("updated_at: %v", d.UpdatedAt))
	b.WriteString(")")
	return b.String()
}

func (d *Deck) applyChange(change *queryx.DeckChange) error {
	if change == nil {
		return nil
	}
	if change.ID.Set {
		d.ID = change.ID.Val
	}
	if change.Name.Set {
		d.Name = change.Name
	}
	if change.CreatedAt.Set {
		d.CreatedAt = change.CreatedAt
	}
	if change.UpdatedAt.Set {
		d.UpdatedAt = change.UpdatedAt
	}
	return nil
}
func (d *Deck) Update(change *queryx.DeckChange) error {
	_, err := d.queries.QueryDeck().Where(d.schema.And(d.schema.DeckID.EQ(d.ID))).UpdateAll(change)
	if err != nil {
		return err
	}

	return d.applyChange(change)
}

func (d *Deck) Delete() error {
	_, err := d.queries.QueryDeck().Delete(d.ID)
	return err
}

func (d *Deck) QueryDeckCards() *DeckCardQuery {
	return d.queries.QueryDeckCard().Where(d.schema.DeckCardDeckID.EQ(d.ID))
}

func (d *Deck) QueryCards() *CardQuery {
	return d.queries.QueryCard().
		Joins("INNER JOIN deck_cards ON deck_cards.card_id = cards.id").
		Where(d.schema.DeckCardDeckID.EQ(d.ID))
}
