// Code generated by queryx, DO NOT EDIT.

package queryx

type CardChange struct {
	ID        BigInt
	Name      String
	Cost      Integer
	Power     Integer
	Ability   String
	DefID     String
	CreatedAt Datetime
	UpdatedAt Datetime
}

func (c *CardChange) Changes() (columns []string, values []interface{}) {
	if c == nil {
		return columns, values
	}
	if c.ID.Set {
		columns = append(columns, "id")
		values = append(values, c.ID)
	}
	if c.Name.Set {
		columns = append(columns, "name")
		values = append(values, c.Name)
	}
	if c.Cost.Set {
		columns = append(columns, "cost")
		values = append(values, c.Cost)
	}
	if c.Power.Set {
		columns = append(columns, "power")
		values = append(values, c.Power)
	}
	if c.Ability.Set {
		columns = append(columns, "ability")
		values = append(values, c.Ability)
	}
	if c.DefID.Set {
		columns = append(columns, "def_id")
		values = append(values, c.DefID)
	}
	if c.CreatedAt.Set {
		columns = append(columns, "created_at")
		values = append(values, c.CreatedAt)
	}
	if c.UpdatedAt.Set {
		columns = append(columns, "updated_at")
		values = append(values, c.UpdatedAt)
	}
	return columns, values
}

func (c *CardChange) SetID(id int64) *CardChange {
	c.ID = NewBigInt(id)
	c.ID.Set = true
	return c
}

func (c *CardChange) SetName(name string) *CardChange {
	c.Name = NewString(name)
	c.Name.Set = true
	return c
}

func (c *CardChange) SetCost(cost int32) *CardChange {
	c.Cost = NewInteger(cost)
	c.Cost.Set = true
	return c
}

func (c *CardChange) SetPower(power int32) *CardChange {
	c.Power = NewInteger(power)
	c.Power.Set = true
	return c
}

func (c *CardChange) SetAbility(ability string) *CardChange {
	c.Ability = NewString(ability)
	c.Ability.Set = true
	return c
}

func (c *CardChange) SetDefID(defID string) *CardChange {
	c.DefID = NewString(defID)
	c.DefID.Set = true
	return c
}

func (c *CardChange) SetCreatedAt(createdAt string) *CardChange {
	c.CreatedAt = NewDatetime(createdAt)
	c.CreatedAt.Set = true
	return c
}

func (c *CardChange) SetUpdatedAt(updatedAt string) *CardChange {
	c.UpdatedAt = NewDatetime(updatedAt)
	c.UpdatedAt.Set = true
	return c
}
