// Code generated by queryx, DO NOT EDIT.

package queryx

type Config struct {
	URL string
}

func NewConfig(env string) *Config {
	switch env {
	case "development":
		return &Config{
			URL: "postgres://postgres:postgres@localhost:5432/ep1_development?sslmode=disable",
		}
	}
	return nil
}
