// Code generated by queryx, DO NOT EDIT.

package queryx

type Schema struct {
	Post            *Table
	PostID          *BigIntColumn
	PostTitle       *StringColumn
	PostContent     *StringColumn
	PostIsPublished *BooleanColumn
	PostCreatedAt   *DatetimeColumn
	PostUpdatedAt   *DatetimeColumn
}

func NewSchema() *Schema {
	post := NewTable("posts")

	return &Schema{
		Post:            post,
		PostID:          post.NewBigIntColumn("id"),
		PostTitle:       post.NewStringColumn("title"),
		PostContent:     post.NewStringColumn("content"),
		PostIsPublished: post.NewBooleanColumn("is_published"),
		PostCreatedAt:   post.NewDatetimeColumn("created_at"),
		PostUpdatedAt:   post.NewDatetimeColumn("updated_at"),
	}
}

func (s *Schema) And(clauses ...*Clause) *Clause {
	return clauses[0].And(clauses[1:]...)
}

func (s *Schema) Or(clauses ...*Clause) *Clause {
	return clauses[0].Or(clauses[1:]...)
}

func (s *Schema) ChangePost() *PostChange {
	return &PostChange{
		ID:          BigInt{},
		Title:       String{},
		Content:     String{},
		IsPublished: Boolean{},
		CreatedAt:   Datetime{},
		UpdatedAt:   Datetime{},
	}
}
