// Code generated by queryx, DO NOT EDIT.

package db

import (
	"database/sql"
	"errors"
	"fmt"
	"snap/db/queryx"
)

type DeckCardQuery struct {
	adapter         *queryx.Adapter
	schema          *queryx.Schema
	queries         Queries
	selectStatement *queryx.SelectStatement
	preload         map[string]bool
	err             error
}

func NewDeckCardQuery(adapter *queryx.Adapter, schema *queryx.Schema, queries Queries) *DeckCardQuery {
	s := queryx.NewSelect().Select("deck_cards.*").From("deck_cards")
	return &DeckCardQuery{
		adapter:         adapter,
		schema:          schema,
		queries:         queries,
		selectStatement: s,
		preload:         make(map[string]bool),
	}
}

func (q *DeckCardQuery) Create(change *queryx.DeckCardChange) (*DeckCard, error) {
	if q.err != nil {
		return nil, q.err
	}

	record := &DeckCard{
		schema:  q.schema,
		queries: q.queries,
	}
	now := queryx.Now("2006-01-02 15:04:05.000")
	if !change.CreatedAt.Set {
		change.SetCreatedAt(now)
	}
	if !change.UpdatedAt.Set {
		change.SetUpdatedAt(now)
	}
	columns, values := change.Changes()
	query, args := queryx.NewInsert().
		Into("deck_cards").
		Columns(columns...).
		Values(values...).
		Returning("id,deck_id,card_id,created_at,updated_at").ToSQL()
	err := q.adapter.QueryOne(query, args...).Scan(record)
	if err != nil {
		return nil, err
	}

	return record, nil
}

func (q *DeckCardQuery) InsertAll(changes []*queryx.DeckCardChange) (int64, error) {
	if q.err != nil {
		return 0, q.err
	}

	if len(changes) == 0 {
		return 0, ErrInsertAllEmptyChanges
	}
	now := queryx.Now("2006-01-02 15:04:05.000")
	for _, change := range changes {
		if !change.CreatedAt.Set {
			change.SetCreatedAt(now)
		}
		if !change.UpdatedAt.Set {
			change.SetUpdatedAt(now)
		}
	}

	s := queryx.NewInsert().Into("deck_cards")
	for i, change := range changes {
		columns, values := change.Changes()
		if i == 0 {
			s.Columns(columns...)
		}
		s.Values(values...)
	}

	query, args := s.ToSQL()
	return q.adapter.Exec(query, args...)
}

func (q *DeckCardQuery) Delete(id int64) (int64, error) {
	query, args := queryx.NewDelete().From("deck_cards").Where(q.schema.DeckCardID.EQ(id)).ToSQL()
	result, err := q.adapter.Exec(query, args...)
	if err != nil {
		return 0, err
	}
	return result, err
}

func (q *DeckCardQuery) Find(id int64) (*DeckCard, error) {
	res, err := q.Where(q.schema.DeckCardID.EQ(id)).First()
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, sql.ErrNoRows
	}
	res.schema = q.schema
	res.queries = q.queries
	return res, err
}

func (q *DeckCardQuery) FindBy(where *queryx.Clause) (*DeckCard, error) {
	return q.Where(where).First()
}

func (q *DeckCardQuery) FindBySQL(query string, args ...interface{}) ([]*DeckCard, error) {
	var deckCardList []DeckCard
	deckCards := make([]*DeckCard, 0)
	err := q.adapter.Query(query, args...).Scan(&deckCardList)
	if err != nil {
		return nil, err
	}
	for i := 0; i < len(deckCardList); i++ {
		deckCards = append(deckCards, &deckCardList[i])
	}
	return deckCards, nil
}

func (q *DeckCardQuery) Where(clause *queryx.Clause) *DeckCardQuery {
	q.selectStatement.Where(clause)
	q.err = clause.Err()
	return q
}

func (q *DeckCardQuery) Select(selection ...string) *DeckCardQuery {
	q.selectStatement.Select(selection...)
	return q
}

func (q *DeckCardQuery) Limit(limit int) *DeckCardQuery {
	q.selectStatement.Limit(limit)
	return q
}

func (q *DeckCardQuery) Offset(offset int) *DeckCardQuery {
	q.selectStatement.Offset(offset)
	return q
}

func (q *DeckCardQuery) Group(group string) *DeckCardQuery {
	q.selectStatement.GroupBy(group)
	return q
}

func (q *DeckCardQuery) Having(having string) *DeckCardQuery {
	q.selectStatement.Having(having)
	return q
}

func (q *DeckCardQuery) Joins(joins string) *DeckCardQuery {
	q.selectStatement.Join(joins)
	return q
}

func (q *DeckCardQuery) Order(order ...string) *DeckCardQuery {
	q.selectStatement.Order(order...)
	return q
}

func (q *DeckCardQuery) PreloadDeck() *DeckCardQuery {
	q.preload["deck"] = true
	return q
}

func (q *DeckCardQuery) preloadDeck(rows []*DeckCard) error {
	ids := []int64{}
	for _, r := range rows {
		if r.DeckID.Valid {
			ids = append(ids, r.DeckID.Val)
		}
	}
	rows1, err := q.queries.QueryDeck().Where(q.schema.DeckID.In(ids)).All()
	if err != nil {
		return err
	}

	m := make(map[int64]*Deck)
	for _, r := range rows1 {
		m[r.ID] = r
	}
	for _, r := range rows {
		if r.DeckID.Valid {
			r.Deck = m[r.DeckID.Val]
		}
	}

	return nil
}

func (q *DeckCardQuery) PreloadCard() *DeckCardQuery {
	q.preload["card"] = true
	return q
}

func (q *DeckCardQuery) preloadCard(rows []*DeckCard) error {
	ids := []int64{}
	for _, r := range rows {
		if r.CardID.Valid {
			ids = append(ids, r.CardID.Val)
		}
	}
	rows1, err := q.queries.QueryCard().Where(q.schema.CardID.In(ids)).All()
	if err != nil {
		return err
	}

	m := make(map[int64]*Card)
	for _, r := range rows1 {
		m[r.ID] = r
	}
	for _, r := range rows {
		if r.CardID.Valid {
			r.Card = m[r.CardID.Val]
		}
	}

	return nil
}

func (q *DeckCardQuery) All() ([]*DeckCard, error) {
	if q.err != nil {
		return nil, q.err
	}
	var rows []DeckCard
	deckcards := make([]*DeckCard, 0)
	query, args := q.selectStatement.ToSQL()
	err := q.adapter.Query(query, args...).Scan(&rows)
	if err != nil {
		return nil, err
	}

	if len(rows) == 0 {
		return deckcards, nil
	}

	for i := range rows {
		rows[i].schema = q.schema
		rows[i].queries = q.queries
		deckcards = append(deckcards, &rows[i])
	}
	if q.preload["deck"] {
		if err := q.preloadDeck(deckcards); err != nil {
			return nil, err
		}
	}
	if q.preload["card"] {
		if err := q.preloadCard(deckcards); err != nil {
			return nil, err
		}
	}

	return deckcards, nil
}

func (q *DeckCardQuery) First() (*DeckCard, error) {
	q.Limit(1)
	results, err := q.All()
	if err != nil {
		return nil, err
	}
	if len(results) > 0 {
		return results[0], nil
	}

	return nil, nil
}

func (q *DeckCardQuery) Count() (int64, error) {
	var res struct {
		Count int64 `db:"count"`
	}
	q.selectStatement.Select("count(*)")
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Count, nil
}

func (q *DeckCardQuery) Avg(v string) (float64, error) {
	var res struct {
		Avg sql.NullFloat64 `db:"avg"`
	}
	q.selectStatement.Select(fmt.Sprintf("avg(%+v)", v))
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Avg.Float64, nil
}

func (q *DeckCardQuery) Sum(v string) (float64, error) {
	var res struct {
		Sum sql.NullFloat64 `db:"sum"`
	}
	q.selectStatement.Select(fmt.Sprintf("sum(%+v)", v))
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Sum.Float64, nil
}

func (q *DeckCardQuery) Max(v string) (float64, error) {
	var res struct {
		Max sql.NullFloat64 `db:"max"`
	}
	q.selectStatement.Select(fmt.Sprintf("max(%+v)", v))
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Max.Float64, nil
}

func (q *DeckCardQuery) Min(v string) (float64, error) {
	var res struct {
		Min sql.NullFloat64 `db:"min"`
	}
	q.selectStatement.Select(fmt.Sprintf("min(%+v)", v))
	query, args := q.selectStatement.ToSQL()
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		return 0, err
	}

	return res.Min.Float64, nil
}

func (q *DeckCardQuery) Exists() (bool, error) {
	q.selectStatement.Select("1 AS one").Limit(1)
	// select 1 as one from users limit 1
	query, args := q.selectStatement.ToSQL()
	var res struct {
		One int64 `db:"one"`
	}
	if err := q.adapter.QueryOne(query, args...).Scan(&res); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return false, nil
		}
		return false, err
	}

	return res.One == 1, nil
}

func (q *DeckCardQuery) UpdateAll(change *queryx.DeckCardChange) (int64, error) {
	if q.err != nil {
		return 0, q.err
	}
	now := queryx.Now("2006-01-02 15:04:05.000")
	if !change.UpdatedAt.Set {
		change.SetUpdatedAt(now)
	}
	columns, values := change.Changes()
	query, args := q.selectStatement.Update().Columns(columns...).Values(values...).ToSQL()
	result, err := q.adapter.Exec(query, args...)
	if err != nil {
		return 0, err
	}
	return result, err
}

func (q *DeckCardQuery) DeleteAll() (int64, error) {
	query, args := q.selectStatement.Delete().ToSQL()
	result, err := q.adapter.Exec(query, args...)
	if err != nil {
		return 0, err
	}
	return result, err
}
